# Site settings
title: "Yonghyun Kim [CV]"
description: "김용현 (Yonghyun Kim) Curriculum Vitae"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Yonghyun Kim"
resume_title:                   "AI+X Student Researcher"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yhkim6087@unist.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-7102-6087"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am an Undergraduate Student at UNIST. I'm majoring in Computer Science and Electrical Engineering. My Major Research Interests are Artificial Intelligence, Human-Computer Interaction. Currently, I am working on research related to Computer Vision, Music, and Deep Learning.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true
resume_section_certificates:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/gagtonight"
  resume_linkedin_url:          "https://www.linkedin.com/in/yonghyunk1m"
  resume_instagram_url:         "https://www.instagram.com/yonghyunk1m/"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart 
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
